# Generated by Django 4.1 on 2022-08-11 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bus_full_name", models.CharField(max_length=255)),
            ],
            options={"verbose_name_plural": "Buses",},
        ),
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tracking_number", models.CharField(max_length=255)),
                ("status", models.CharField(max_length=255)),
                ("receiver_name", models.CharField(max_length=255)),
                ("receiver_phone_number", models.CharField(max_length=255)),
                ("sender_phone_number", models.CharField(max_length=255)),
                ("delivery_destination", models.CharField(max_length=255)),
                ("number_of_packages", models.IntegerField(default=1)),
                ("price", models.FloatField(default=0.0)),
                ("departure_date", models.DateField()),
                ("departure_time", models.DateField()),
                ("date_time_received", models.DateTimeField(auto_now_add=True)),
                ("location", models.CharField(default="0.0, 0.0", max_length=255)),
                (
                    "bus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="global.bus"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BusCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=50)),
                ("company_phone_number", models.CharField(max_length=50)),
                ("company_email", models.EmailField(max_length=64)),
                ("address", models.CharField(max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Login Username",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Bus Companies",},
        ),
        migrations.AddField(
            model_name="bus",
            name="bus_company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="global.buscompany"
            ),
        ),
        migrations.AddField(
            model_name="bus",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
