# Generated by Django 4.1 on 2022-08-11 12:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("global", "0003_rename_buscompany_couriercompany_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="departure_time",
            field=models.TimeField(default=datetime.time(12, 15, 7, 814425)),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="transit_time",
            field=models.TimeField(default=datetime.time(12, 15, 7, 814450)),
        ),
    ]
