# Generated by Django 4.1 on 2022-08-12 12:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("global", "0006_alter_package_tracking_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="current_town",
            field=models.CharField(
                default="Lusaka Intercity Bus Station", max_length=255
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="package",
            name="status",
            field=models.CharField(
                default="processed at <django.db.models.fields.CharField>",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="package",
            name="tracking_number",
            field=models.CharField(default="50266981", max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="departure_time",
            field=models.TimeField(default=datetime.time(14, 31, 41, 147159)),
        ),
    ]
