# Generated by Django 4.1 on 2022-08-12 13:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("global", "0008_rename_location_package_current_coordinates_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="package", name="departure_time", field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="package",
            name="tracking_number",
            field=models.CharField(
                default="0011997196", editable=False, max_length=255, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="departure_time",
            field=models.TimeField(default=datetime.time(15, 28, 42, 708656)),
        ),
    ]
