# Generated by Django 4.1 on 2022-08-12 13:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("global", "0009_alter_package_departure_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="package", name="departure_time", field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="package",
            name="tracking_number",
            field=models.CharField(
                default="2470595922", editable=False, max_length=255, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="departure_time",
            field=models.TimeField(default=datetime.time(15, 29, 41, 90409)),
        ),
    ]
