# Generated by Django 4.1 on 2022-08-12 13:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("global", "0010_alter_package_departure_time_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="package", old_name="current_town", new_name="starting_town",
        ),
        migrations.AlterField(
            model_name="package",
            name="tracking_number",
            field=models.CharField(
                default="9463776268", editable=False, max_length=255, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="departure_time",
            field=models.TimeField(default=datetime.time(15, 41, 0, 354194)),
        ),
    ]
