# Generated by Django 4.1 on 2022-08-22 14:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("global", "0013_alter_package_tracking_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="couriercompany",
            name="account_balance",
            field=models.FloatField(
                default=0.0,
                help_text="Initial account balance for this company in Zambian Kwacha",
            ),
        ),
        migrations.AddField(
            model_name="couriercompany",
            name="all1zed_commission",
            field=models.FloatField(
                default=5.0,
                help_text="Commission charged per Package Sent (In Zambian Kwacha)",
            ),
        ),
        migrations.AlterField(
            model_name="package",
            name="tracking_number",
            field=models.CharField(
                default="8961038629", editable=False, max_length=255, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="departure_time",
            field=models.TimeField(default=datetime.time(16, 6, 26, 293930)),
        ),
    ]
