# Generated by Django 4.1 on 2022-09-01 12:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("global", "0016_alter_package_tracking_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="vehicle", name="user",),
        migrations.AlterField(
            model_name="package",
            name="tracking_number",
            field=models.CharField(
                default="1835761381", editable=False, max_length=255, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="departure_time",
            field=models.TimeField(default=datetime.time(14, 0, 44, 560666)),
        ),
    ]
