# Generated by Django 4.1 on 2022-09-01 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("global", "0018_alter_package_tracking_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="vehicle", name="transit_time",),
        migrations.AlterField(
            model_name="package",
            name="tracking_number",
            field=models.CharField(
                default="6736102071", editable=False, max_length=255, unique=True
            ),
        ),
    ]
