# Generated by Django 4.1.1 on 2022-09-20 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CourierCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=50)),
                (
                    "company_logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="logos",
                        verbose_name="Upload Company logo.",
                    ),
                ),
                ("company_phone_number", models.CharField(max_length=50)),
                ("company_email", models.EmailField(max_length=64)),
                ("address", models.CharField(max_length=100)),
                (
                    "all1zed_commission",
                    models.FloatField(
                        default=5.0,
                        help_text="Commission charged per Package Sent (In Zambian Kwacha)",
                    ),
                ),
                (
                    "number_of_packages",
                    models.IntegerField(
                        default=0, help_text="Initial number of packages."
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Login Username",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Courier Companies",},
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vehicle_full_name", models.CharField(max_length=255)),
                ("departure_time", models.TimeField()),
                (
                    "transit_time",
                    models.IntegerField(
                        help_text="Number of hours it takes for vehicle to reach the destination."
                    ),
                ),
                (
                    "courier_company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="general.couriercompany",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Vehicles",},
        ),
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tracking_number",
                    models.CharField(
                        default="2693230689",
                        editable=False,
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("receiver_name", models.CharField(max_length=255)),
                ("receiver_phone_number", models.CharField(max_length=255)),
                ("sender_phone_number", models.CharField(max_length=255)),
                ("delivery_town", models.CharField(max_length=255)),
                ("starting_town", models.CharField(default="Lusaka", max_length=255)),
                ("number_of_packages", models.IntegerField(default=1)),
                ("price", models.FloatField(default=0.0)),
                ("departure_date", models.DateField(blank=True, null=True)),
                ("departure_time", models.TimeField()),
                ("processed_date_time", models.DateTimeField(auto_now_add=True)),
                ("transit_date_time", models.DateTimeField(blank=True, null=True)),
                (
                    "ready_for_collection_date_time",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("collected_date_time", models.DateTimeField(blank=True, null=True)),
                (
                    "processed_status",
                    models.BooleanField(blank=True, default=True, null=True),
                ),
                (
                    "transit_status",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "transit_message",
                    models.CharField(default="In transit.", max_length=255),
                ),
                (
                    "ready_for_collection_status",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "collected_status",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "current_coordinates",
                    models.CharField(default="0.0, 0.0", max_length=255),
                ),
                ("previous_town", models.CharField(default="...", max_length=255)),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="general.vehicle",
                    ),
                ),
            ],
        ),
    ]
