# Generated by Django 4.1.1 on 2022-09-20 23:45

from django.db import migrations, models
import general.models


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="couriercompany",
            name="company_initials",
            field=models.CharField(default="All1Zed", help_text="e.g FM", max_length=5),
        ),
        migrations.AlterField(
            model_name="package",
            name="tracking_number",
            field=models.CharField(
                default=general.models.calculate_tracking_number,
                editable=False,
                max_length=255,
                unique=True,
            ),
        ),
    ]
