# Generated by Django 4.1 on 2022-08-11 11:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("general", "0002_rename_bus_vehicle"),
    ]

    operations = [
        migrations.RenameModel(old_name="BusCompany", new_name="CourierCompany",),
        migrations.AlterModelOptions(
            name="couriercompany", options={"verbose_name_plural": "Courier Companies"},
        ),
        migrations.AlterModelOptions(
            name="vehicle", options={"verbose_name_plural": "Vehicles"},
        ),
        migrations.RenameField(
            model_name="package", old_name="bus", new_name="vehicle",
        ),
        migrations.RenameField(
            model_name="vehicle", old_name="bus_company", new_name="courier_company",
        ),
        migrations.RenameField(
            model_name="vehicle",
            old_name="bus_full_name",
            new_name="vehicle_full_name",
        ),
    ]
