# Generated by Django 4.1.1 on 2022-10-06 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0003_alter_package_tracking_number"),
    ]

    operations = [
        migrations.RemoveField(model_name="couriercompany", name="company_initials",),
        migrations.AddField(
            model_name="package",
            name="package_value",
            field=models.IntegerField(default=0.0),
        ),
        migrations.AddField(
            model_name="package",
            name="processed_by",
            field=models.CharField(default="Not Applicable", max_length=255),
        ),
        migrations.AlterField(
            model_name="package",
            name="tracking_number",
            field=models.CharField(editable=False, max_length=255),
        ),
    ]
