# Generated by Django 4.1 on 2022-08-11 14:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0004_vehicle_departure_time_vehicle_transit_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="departure_time",
            field=models.TimeField(default=datetime.time(16, 21, 42, 19893)),
        ),
        migrations.AlterField(
            model_name="vehicle", name="transit_time", field=models.IntegerField(),
        ),
    ]
