# Generated by Django 4.1.1 on 2022-11-11 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0004_remove_couriercompany_company_initials_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="package",
            name="package_value",
            field=models.IntegerField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name="package",
            name="processed_by",
            field=models.CharField(
                default="Not Applicable for this package", max_length=255
            ),
        ),
    ]
