# Generated by Django 4.1 on 2022-08-12 13:24

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0007_package_current_town_alter_package_status_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="package", old_name="location", new_name="current_coordinates",
        ),
        migrations.RenameField(
            model_name="package",
            old_name="delivery_destination",
            new_name="delivery_town",
        ),
        migrations.RemoveField(model_name="package", name="status",),
        migrations.AddField(
            model_name="package",
            name="collected_date_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="collected_status",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="processed_date_time",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="package",
            name="processed_status",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="ready_for_collection_date_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="ready_for_collection_status",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="transit_date_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="transit_status",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="package",
            name="current_town",
            field=models.CharField(default="Lusaka", max_length=255),
        ),
        migrations.AlterField(
            model_name="package",
            name="departure_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="package",
            name="tracking_number",
            field=models.CharField(default="47199322", max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="departure_time",
            field=models.TimeField(default=datetime.time(15, 24, 35, 118040)),
        ),
    ]
