# Generated by Django 4.1 on 2022-08-12 13:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0011_rename_current_town_package_starting_town_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="package", name="date_time_received",),
        migrations.AlterField(
            model_name="package",
            name="tracking_number",
            field=models.CharField(
                default="2743876196", editable=False, max_length=255, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="departure_time",
            field=models.TimeField(default=datetime.time(15, 47, 45, 379604)),
        ),
    ]
