# Generated by Django 4.1 on 2022-08-22 13:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("general", "0012_remove_package_date_time_received_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="package",
            name="tracking_number",
            field=models.CharField(
                default="3080733133", editable=False, max_length=255, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="departure_time",
            field=models.TimeField(default=datetime.time(15, 27, 21, 406856)),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="transit_time",
            field=models.IntegerField(
                help_text="Number of hours it takes for vehicle to reach the destination."
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Vehicle Admin",
            ),
        ),
    ]
