# Generated by Django 4.1 on 2022-09-01 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0019_remove_vehicle_transit_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="transit_time",
            field=models.IntegerField(
                default=1,
                help_text="Number of hours it takes for vehicle to reach the destination.",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="package",
            name="tracking_number",
            field=models.CharField(
                default="3290677045", editable=False, max_length=255, unique=True
            ),
        ),
    ]
