# Generated by Django 4.1 on 2022-09-05 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0020_vehicle_transit_time_alter_package_tracking_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="previous_town",
            field=models.CharField(default="...", max_length=255),
        ),
        migrations.AddField(
            model_name="package",
            name="transit_message",
            field=models.CharField(default="In transit.", max_length=255),
        ),
        migrations.AlterField(
            model_name="package",
            name="tracking_number",
            field=models.CharField(
                default="2720257887", editable=False, max_length=255, unique=True
            ),
        ),
    ]
