# Generated by Django 4.1 on 2022-09-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0021_package_previous_town_package_transit_message_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="package",
            name="tracking_number",
            field=models.CharField(
                default="9300296192", editable=False, max_length=255, unique=True
            ),
        ),
    ]
