# Generated by Django 4.1.1 on 2022-09-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0026_alter_package_tracking_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="couriercompany",
            name="company_logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="logos",
                verbose_name="Upload Company logo.",
            ),
        ),
        migrations.AlterField(
            model_name="package",
            name="tracking_number",
            field=models.CharField(
                default="8755365349", editable=False, max_length=255, unique=True
            ),
        ),
    ]
