# Generated by Django 4.1.1 on 2022-09-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name="couriercompany",
            name="company_logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="logos",
                verbose_name="Upload Company logo.",
            ),
        ),
    ]
