# Generated by Django 4.1 on 2022-09-13 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KazangSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_uuid", models.CharField(editable=False, max_length=255)),
                ("date_time_created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("session_uuid", models.CharField(max_length=255)),
                ("date_time_created", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("successful", "successful"), ("failed", "failed")],
                        max_length=50,
                    ),
                ),
                ("product_id", models.IntegerField()),
                ("amount", models.FloatField()),
                ("phone_number", models.CharField(max_length=15)),
                (
                    "type",
                    models.CharField(
                        choices=[("cash_in", "cash_in"), ("payment", "payment")],
                        max_length=255,
                    ),
                ),
                (
                    "request_reference",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("provider_reference", models.CharField(max_length=255)),
            ],
        ),
    ]
