# Generated by Django 4.1.1 on 2022-09-20 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PackageTracking", "0001_initial"),
    ]

    operations = [

    ]
