# Generated by Django 4.1 on 2022-09-13 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PackageTracking", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PricingPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tier_name",
                    models.CharField(
                        help_text="Pricing Plan Tier Name e.g Gold Standard Plan.",
                        max_length=255,
                    ),
                ),
                ("number_of_packages", models.IntegerField()),
                ("price", models.FloatField()),
            ],
        ),
    ]
