# Generated by Django 4.1.1 on 2022-09-21 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PackageTracking", "0002_kazangsession"),
    ]

    operations = [

    ]
