# Generated by Django 4.1.1 on 2022-09-22 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PackageTracking", "0003_kazangsession"),
    ]

    operations = [
        migrations.CreateModel(
            name="KazangSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_uuid", models.CharField(editable=False, max_length=255)),
                ("date_time_created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
